<div class="alert alert-warning" style="margin: 10px"><strong>WARNING!</strong> do NOT run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

In [1]:
import os
import matplotlib.pyplot as plt
import scikitplot as skplt
import numpy as np
import pandas as pd
from IPython.display import display


# <font color=crimson>   Exercise - Combining Multiple Learners </font> 
For the Wisconsin Cancer dataset, create the following ensemble classifiers:

Bagged decision tree

Random forest

Adaboost

Using cross-validation (proportion 0.7/0.3).

Check the accuracy for in out-of-sample data sets.


BONUS: Staking example

## <font color=crimson>  Load Breast Cancer  data </font> 

In [2]:
# RUN THIS CELL
df = pd.read_csv("../data/BreastCancer.csv")
target = df['diagnosis']
del df['diagnosis']
del df['id']

display(df.head(2))
display(target.head(2))

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

0    M
1    M
Name: diagnosis, dtype: object

## <font color=crimson>  Create a decision tree </font> 

In [3]:
# RUN THIS CELL - A decision tree is created for  comparison purposes at the end

from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df, target, test_size=.3, random_state=3680)

modelTree = tree.DecisionTreeClassifier()
modelTree.fit(X_train, y_train)
print('in sample accuracy:',modelTree.score(X_train, y_train))
print('out sample accuracy:',modelTree.score(X_test, y_test))

y_pred= modelTree.predict(X_test)
print('DecisionTree Classifier confusion matrice: \n')
print(confusion_matrix(y_test,y_pred))

in sample accuracy: 1.0
out sample accuracy: 0.9707602339181286
DecisionTree Classifier confusion matrice: 

[[106   3]
 [  2  60]]


## <font color=crimson>  Bagging Classifier example </font> 

In [4]:
# RUN THIS CELL - ALL sklearn packages are being uploaded here.
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier, RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB



In [5]:
## CODE HERE - Bagging Classifier example

In [6]:
#DON'T WRITE HERE
seed = 1
num_trees = 100

cart = DecisionTreeClassifier()
BAG = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)
BAG.fit(X_train, y_train)
predictions1 =BAG.predict(X_test)
cm = confusion_matrix(y_test, predictions1)
display(cm)
print('Classification report\n',classification_report(y_test, BAG.predict(X_test)))

array([[109,   0],
       [  3,  59]], dtype=int64)

Classification report
               precision    recall  f1-score   support

           B       0.97      1.00      0.99       109
           M       1.00      0.95      0.98        62

    accuracy                           0.98       171
   macro avg       0.99      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



## <font color=crimson>  Random Forest example </font> 

In [7]:
## CODE HERE - Random Forest Example

In [8]:
## DON'T WRITE HERE
seed = 1
num_trees = 300
max_features = 6
seed = 1
num_trees = 300
max_features = 6
RF = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
RF.fit(X_train,y_train)

print('testing CM\n',confusion_matrix(y_test, RF.predict(X_test)))
print('Classification report\n',classification_report(y_test, RF.predict(X_test)))

testing CM
 [[108   1]
 [  2  60]]
Classification report
               precision    recall  f1-score   support

           B       0.98      0.99      0.99       109
           M       0.98      0.97      0.98        62

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



## <font color=crimson>  ADABOOST example </font> 

In [9]:
## CODE HERE

In [10]:
# DON'T WRITE HERE - Adaboost Example

seed = 1
num_trees = 700
ADA = AdaBoostClassifier(
    DecisionTreeClassifier(),
    n_estimators=num_trees, random_state=seed
)
ADA.fit(X_train,y_train)

print('Confusion Matrix\n',confusion_matrix(y_test, ADA.predict(X_test)))
print('Classification report\n',classification_report(y_test, ADA.predict(X_test)))


Confusion Matrix
 [[105   4]
 [  3  59]]
Classification report
               precision    recall  f1-score   support

           B       0.97      0.96      0.97       109
           M       0.94      0.95      0.94        62

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



## <font color=crimson>  Voting Classifer example </font> 

In [11]:
## CODE HERE- Voting Classifier
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler


In [12]:
# DON'T WRITE HERE - Voting Classifier Example

scl = StandardScaler()
X_train_scaled = pd.DataFrame(scl.fit_transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scl.transform(X_test), columns=X_train.columns)


seed =42
LRclf  = LogisticRegression(solver='lbfgs', multi_class='multinomial',max_iter=250,random_state=seed)
NBclf  = GaussianNB()
KNNclf = KNeighborsClassifier(n_neighbors=3)

Ensclf = VotingClassifier(estimators=[  ('lr', LRclf), ('nb', NBclf), ('knn', KNNclf)], voting='soft')

Ensclf.fit(X_train_scaled, y_train)
print('testing CM\n',confusion_matrix(y_test, Ensclf.predict(X_test_scaled )))
print('Classification report\n',classification_report(y_test, Ensclf.predict(X_test_scaled )))


testing CM
 [[108   1]
 [  1  61]]
Classification report
               precision    recall  f1-score   support

           B       0.99      0.99      0.99       109
           M       0.98      0.98      0.98        62

    accuracy                           0.99       171
   macro avg       0.99      0.99      0.99       171
weighted avg       0.99      0.99      0.99       171



In [13]:
for clf in [LRclf, NBclf,KNNclf, Ensclf]:
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))


LogisticRegression 0.9766081871345029
GaussianNB 0.9766081871345029
KNeighborsClassifier 0.9824561403508771
VotingClassifier 0.9883040935672515


## <font color=crimson>  Stacking example </font> 

### <font color=crimson> Single-Layer Stacking Classifier example </font> 

In [14]:
# Building a Single-Layer Stacking Classifier
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

base_learners = [
    ('rf_1', RandomForestClassifier(random_state=42)),
    ('nb_1', GaussianNB())
]
stack_clf = StackingClassifier(estimators=base_learners, final_estimator=make_pipeline(StandardScaler(),LogisticRegression()))
print("Stacking: ", stack_clf.fit(X_train, y_train).score(X_test, y_test))


Stacking:  0.9824561403508771


### <font color=crimson> Multi-Layer Stacking Classifier example </font> 

In [15]:
# Building a Multi-Layer Stacking Classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
base_2_learners = [
    ('knn_1',make_pipeline(StandardScaler(), KNeighborsClassifier()) ),
    ('rf_2', RandomForestClassifier(n_estimators=100, random_state=42))
]

layer2 = StackingClassifier(estimators=base_2_learners, final_estimator=make_pipeline(StandardScaler(),LogisticRegression()))
stack_multi_clf = StackingClassifier(estimators=base_learners, final_estimator=layer2)

print("Multi-layer Stacking: ", stack_multi_clf.fit(X_train, y_train).score(X_test, y_test))

Multi-layer Stacking:  0.9766081871345029


### Exercise 2 - Expected Values


Take the confusion matrices of the previous exercise, assume:

Cost 1 for FP

Cost 100 for FN

Cost 0 for TP

Cost 0 for TN 

Given the costs, which is the best classifier?


$EV[X] = \sum_{i=1}^{k}x_ip_i=x_1p_1+x_2p_2+\cdots+x_kp_k$ 


$EV[X]= b(Y,p)\times p(Y,p) + b(Y,n)\times p(Y,n) +b(N,n)\times p(N,n)+b(N,p)\times p(N,p)  $

$EV[X]= 0\times p(Y,p) - 100\times p(Y,n) + 0\times p(N,n) - 1\times p(N,p)  $


CM from ENsclf
 [[104   4]
 [  6  57]]
 
 p(Y,p) = 57/171  = CM[1,1]/171
 
 p(N,n) = 104/171 = CM[0,0]/171
 
 p(Y,n) = 6/171 = CM[1,0]/171
 
 p(N,p) = 4/171 = CM[0,1]/171

In [16]:
confusion_matrix(y_test, RF.predict(X_test_scaled ))

array([[109,   0],
       [ 52,  10]], dtype=int64)

In [17]:
## CODE HERE - Expected values
for mod, name in zip([Ensclf,ADA, RF, BAG],['Ensclf','ADA','RF', 'BAG']):
    PFP = 100*confusion_matrix(y_test, mod.predict(X_test))[0,1]/confusion_matrix(y_test, mod.predict(X_test)).sum()
    PFN = 100*confusion_matrix(y_test, mod.predict(X_test))[1,0]/confusion_matrix(y_test, mod.predict(X_test)).sum()
    EV = -100*PFN - 1*PFP
    print('Expected Value for',name, 'is', EV)

Expected Value for Ensclf is -63.74269005847953
Expected Value for ADA is -177.77777777777777
Expected Value for RF is -117.54385964912281
Expected Value for BAG is -175.43859649122805
